### ISSUE TITLE
IMDS not accessible from docker container

### ISSUE THREAD

**Issue by jesseduffield** [runs-on/runs-on#158] opened 2024-11-02 08:52 UTC
I'm trying to run AWS commands from within a docker container on my CI runner and it appears that it's failing to get credentials from IMDS:

```
	* No valid credential sources found: Please see https://registry.terraform.io/providers/hashicorp/aws
for more information about providing credentials.
Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, access disabled to EC2 IMDS via client option, or "AWS_EC2_METADATA_DISABLED" environment 
```

Previously I directly stored IAM user credentials in github but I've switched to instead using the EC2InstanceCustomPolicy cloudformation param. Other steps in the CI workflow that are outside of docker are still able to successfully do things (e.g. pushing docker images to ECR).

I wonder if this is related to what this comment says about permitting more than one network hop to access IMDS: https://github.com/hashicorp/terraform-provider-aws/issues/23110#issuecomment-1035712587

If so, could we up the number of allowed network hops so that we can access IMDS from within a docker container?

Thanks

**Comment by jesseduffield** [comment] 2024-11-02 09:10
Also for the record I'm using this workaround currently to fetch the credentials directly from IMDS:

```yml
- name: Export temp AWS credentials from IMDS
  shell: bash
  run: |
    TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
    ROLE_NAME=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s http://169.254.169.254/latest/meta-data/iam/security-credentials/)
    CREDENTIALS=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s http://169.254.169.254/latest/meta-data/iam/security-credentials/$ROLE_NAME)
    echo "AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | jq -r .AccessKeyId)" >> $GITHUB_ENV
    echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r .SecretAccessKey)" >> $GITHUB_ENV
    echo "AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r .Token)" >> $GITHUB_ENV
```

**Comment by crohr** [comment] 2024-11-06 08:46
@jesseduffield This is surprising because the number of allowed hops is already set to 2, to allow for just this use case: https://github.com/runs-on/runs-on/blob/cd56b4ad3d5a2ba7ce2f11a7b31a48f2d3096ea7/cloudformation/template-v2.5.8.yaml#L756

I'll try to reproduce.

**Comment by crohr** [comment] 2024-12-05 13:55
@jesseduffield sorry for not getting back to you earlier. I finally took some time to try and reproduce with the following step within a job launched with RunsOn:

```yaml
      - name: "Make sure RunsOn role can be used from within a container"
        run: |
          dd if=/dev/urandom of=random.bin bs=1M count=10
          ls -lh random.bin
          docker run --rm -v $(pwd):/data -a stdout -a stderr --entrypoint aws amazon/aws-cli:latest s3 cp /data/random.bin s3://${{ env.RUNS_ON_S3_BUCKET_CACHE }}/cache/
```

And it works fine:

```
10+0 records in
10+0 records out
-rw-r--r-- 1 runner runner 10M Dec  5 13:52 random.bin
10485760 bytes (10 MB, 10 MiB) copied, 0.030292 s, 346 MB/s
Unable to find image 'amazon/aws-cli:latest' locally
latest: Pulling from amazon/aws-cli
899046e4a240: Pulling fs layer
3cfd[21](https://github.com/runs-on/test/actions/runs/12181126577/job/33977023493#step:8:22)d0355d: Pulling fs layer
eef39247834a: Pulling fs layer
9cf181baa99f: Pulling fs layer
e3d938d30940: Pulling fs layer
9cf181baa99f: Waiting
e3d938d30940: Waiting
3cfd21d0355d: Verifying Checksum
3cfd21d0355d: Download complete
9cf181baa99f: Verifying Checksum
9cf181baa99f: Download complete
e3d938d30940: Download complete
899046e4a240: Verifying Checksum
899046e4a240: Download complete
eef39247834a: Verifying Checksum
eef39247834a: Download complete
899046e4a240: Pull complete
3cfd21d0355d: Pull complete
eef39247834a: Pull complete
9cf181baa99f: Pull complete
e3d938d30940: Pull complete
Digest: sha256:e9be6e33e64c4b556849bc215b24872e2cfb49d32b1704af9f1825ae9251d2ef
Status: Downloaded newer image for amazon/aws-cli:latest
Completed 256.0 KiB/10.0 MiB (3.1 MiB/s) with 1 file(s) remaining
Completed 512.0 KiB/10.0 MiB (6.1 MiB/s) with 1 file(s) remaining
Completed 768.0 KiB/10.0 MiB (9.0 MiB/s) with 1 file(s) remaining
Completed 1.0 MiB/10.0 MiB (11.8 MiB/s) with 1 file(s) remaining 
Completed 1.2 MiB/10.0 MiB (14.5 MiB/s) with 1 file(s) remaining 
Completed 1.5 MiB/10.0 MiB (17.3 MiB/s) with 1 file(s) remaining 
Completed 1.8 MiB/10.0 MiB (19.9 MiB/s) with 1 file(s) remaining 
Completed 2.0 MiB/10.0 MiB ([22](https://github.com/runs-on/test/actions/runs/12181126577/job/33977023493#step:8:23).5 MiB/s) with 1 file(s) remaining 
Completed 2.2 MiB/10.0 MiB (17.4 MiB/s) with 1 file(s) remaining 
Completed 2.5 MiB/10.0 MiB (19.2 MiB/s) with 1 file(s) remaining 
Completed 2.8 MiB/10.0 MiB (21.0 MiB/s) with 1 file(s) remaining 
Completed 3.0 MiB/10.0 MiB (22.8 MiB/s) with 1 file(s) remaining 
Completed 3.2 MiB/10.0 MiB ([24](https://github.com/runs-on/test/actions/runs/12181126577/job/33977023493#step:8:25).6 MiB/s) with 1 file(s) remaining 
Completed 3.5 MiB/10.0 MiB (26.2 MiB/s) with 1 file(s) remaining 
Completed 3.8 MiB/10.0 MiB ([27](https://github.com/runs-on/test/actions/runs/12181126577/job/33977023493#step:8:28).7 MiB/s) with 1 file(s) remaining 
Completed 4.0 MiB/10.0 MiB ([29](https://github.com/runs-on/test/actions/runs/12181126577/job/33977023493#step:8:30).2 MiB/s) with 1 file(s) remaining 
Completed 4.2 MiB/10.0 MiB ([30](https://github.com/runs-on/test/actions/runs/12181126577/job/33977023493#step:8:31).7 MiB/s) with 1 file(s) remaining 
Completed 4.5 MiB/10.0 MiB ([32](https://github.com/runs-on/test/actions/runs/12181126577/job/33977023493#step:8:33).3 MiB/s) with 1 file(s) remaining 
Completed 4.8 MiB/10.0 MiB ([33](https://github.com/runs-on/test/actions/runs/12181126577/job/33977023493#step:8:34).8 MiB/s) with 1 file(s) remaining 
Completed 5.0 MiB/10.0 MiB (35.2 MiB/s) with 1 file(s) remaining 
Completed 5.2 MiB/10.0 MiB ([36](https://github.com/runs-on/test/actions/runs/12181126577/job/33977023493#step:8:37).8 MiB/s) with 1 file(s) remaining 
Completed 5.5 MiB/10.0 MiB (38.2 MiB/s) with 1 file(s) remaining 
Completed 5.8 MiB/10.0 MiB ([39](https://github.com/runs-on/test/actions/runs/12181126577/job/33977023493#step:8:40).6 MiB/s) with 1 file(s) remaining 
Completed 6.0 MiB/10.0 MiB (41.1 MiB/s) with 1 file(s) remaining 
Completed 6.2 MiB/10.0 MiB ([42](https://github.com/runs-on/test/actions/runs/12181126577/job/33977023493#step:8:43).5 MiB/s) with 1 file(s) remaining 
Completed 6.5 MiB/10.0 MiB ([43](https://github.com/runs-on/test/actions/runs/12181126577/job/33977023493#step:8:44).9 MiB/s) with 1 file(s) remaining 
Completed 6.8 MiB/10.0 MiB ([45](https://github.com/runs-on/test/actions/runs/12181126577/job/33977023493#step:8:46).3 MiB/s) with 1 file(s) remaining 
Completed 7.0 MiB/10.0 MiB ([46](https://github.com/runs-on/test/actions/runs/12181126577/job/33977023493#step:8:47).4 MiB/s) with 1 file(s) remaining 
Completed 7.2 MiB/10.0 MiB (47.6 MiB/s) with 1 file(s) remaining 
Completed 7.5 MiB/10.0 MiB (48.8 MiB/s) with 1 file(s) remaining 
Completed 7.8 MiB/10.0 MiB (50.0 MiB/s) with 1 file(s) remaining 
Completed 8.0 MiB/10.0 MiB (51.2 MiB/s) with 1 file(s) remaining 
Completed 8.2 MiB/10.0 MiB (52.4 MiB/s) with 1 file(s) remaining 
Completed 8.5 MiB/10.0 MiB (53.7 MiB/s) with 1 file(s) remaining 
Completed 8.8 MiB/10.0 MiB (54.9 MiB/s) with 1 file(s) remaining 
Completed 9.0 MiB/10.0 MiB (56.0 MiB/s) with 1 file(s) remaining 
Completed 9.2 MiB/10.0 MiB (57.1 MiB/s) with 1 file(s) remaining 
Completed 9.5 MiB/10.0 MiB (58.3 MiB/s) with 1 file(s) remaining 
Completed 9.8 MiB/10.0 MiB (59.6 MiB/s) with 1 file(s) remaining 
Completed 10.0 MiB/10.0 MiB (60.7 MiB/s) with 1 file(s) remaining
upload: ../data/random.bin to s3://runs-on-s3bucketcache-ovygb9vpc17m/cache/random.bin
```

Could you share a bit more about your setup maybe? Or do you override some `AWS_*` keys in previous steps of your workflow?

**Comment by crohr** [comment] 2024-12-12 14:52
Closing for now, please reopen if you are able to troubleshoot a bit further.

**Closed by crohr** 2024-12-12 14:52 UTC
Labels: invalid
